import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import navStyles from "../styles/Navbar.module.css";
import firstsecStyles from "../styles/firstSec.module.css";
import worksecStyles from "../styles/workSec.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div className={navStyles.navbar}>
        <div className={navStyles.branding}>
          <img src="/anadyanair-logo.png" alt="" />
          {/* <Image
            className={navStyles.logo}
            src="/anadyanair-logo.png"
            width={30}
            height={30}
          ></Image> */}
          <p className={navStyles.text}>Anadya Nair - Student, Developer.</p>
        </div>

        <div className={navStyles.buttonNav}>
          <Link href="/">
            <ul>
              <li>
                <a>About</a>
              </li>
            </ul>
          </Link>
          <span className={navStyles.spacingSpan}></span>
          <Link href="/">
            <ul>
              <li>
                <a>Works</a>
              </li>
            </ul>
          </Link>
          <span className={navStyles.spacingSpan}></span>
          <Link href="/">
            <ul>
              <li>
                <a>Blog</a>
              </li>
            </ul>
          </Link>
          <span className={navStyles.spacingSpan}></span>
          <Link href="/">
            <ul>
              <li>
                <a>Contact</a>
              </li>
            </ul>
          </Link>
        </div>
      </div>

      <div className={firstsecStyles.section}>
        <h1 className={firstsecStyles.headline}>
          Developer & designer of interactive
          <br /> applications which you can easily use.
        </h1>

        <img src="/Frame 6.png" alt="" />
      </div>

      <div className={firstsecStyles.section2}>
        <div className={firstsecStyles.paragraphs}>
          <p>
            I am a keen learner and am curious about <br /> many things.
            Watching and experiencing <br /> tech around me is what made me
            develop <br /> an interest and to learn it.
          </p>
          <span className={firstsecStyles.spacingSpan}></span>
          <p>
            I’ve now practiced hands on <br /> programming frameworks and <br />{" "}
            languages and am looking forward <br /> to build something amazing.
          </p>
        </div>
      </div>

      <div className={worksecStyles.section3}>
        <div className={worksecStyles.paragraphs}>
          <p>
            I make things with Realisation, <br /> Knowledge, Dedication, Hope{" "}
            <br /> and Acceptance.
          </p>
          <span className={worksecStyles.spacingSpan}></span>
          <p>
            This is a brief <br /> selection of my works. <br />
            <Link className={worksecStyles.Link} href="/">
              <a>Take a look at all of them →</a>
            </Link>{" "}
          </p>
        </div>
      </div>
    </div>
  );
}
